### PR TITLE
Release tags

### PR DESCRIPTION
**Pull request by amarcum**
Auto increment git tags based on commit messages, create a GitHub release, and upload those releases when on master.

### CODE REVIEW

**Comment by amarcum** [comment]
@deitch here are the CI updates I mentioned before. And here is an example release that it will produce

https://github.com/jarvisfriends/go-pcap/releases/tag/v0.0.2

**Comment by deitch** [comment]
I like the idea of building binaries and creating a release for tags. I am less in favour of creating a new tag for each commit to `master`. Does that make sense? Usually, you can have lots of commits between a release, cutting only when desired, usually by creating a tag.

Why would I want it this way, rather than when I create a tag?

As an aside, I never liked the fact that GitHub does not let you PR for tags, i.e. you have to create it and push directly to a `master`, but that is a side issue.

**Comment by amarcum** [comment]
I completely understand your preference for creating tags manually. That approach definitely makes sense for many projects!

The automated patch-increment approach I suggested is just an option – it can be useful for projects that want frequent releases. A key goal is to have regular updates to address security concerns and ensure a stable go.mod reference (so less hashes and more version numbers).

If you'd like, I can add a second workflow without the automatic trigger on master. This workflow would let you trigger the tagging, release creation, and binary upload process manually, whenever you're ready to create a new release. You can trigger it from the Actions tab on GitHub after it has first been merged to master. This way, you have the flexibility to release when it makes the most sense!

**Comment by amarcum** [comment]
I created the more flexible option in a new PR, if you are good with one of them please close the other. I don't have a strong preference to either one, its up to you!
Thank you again for having this library, its awesome!

**Comment by deitch** [comment]
Closing in favour of #56

**Pull request closed without merging**
