### PR TITLE
Updated to gopacket/gopacket

### PR DESCRIPTION
**Pull request by amarcum**
Updated to the maintained gopacket/gopacket instead of google/gopacket
Updated minimum go version to match gopacket/gopacket
Added a really simple unit test

### CODE REVIEW

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
This is great, thank you. The one you switched to is a fork of the original, so it should work well. If CI passes, I am comfortable with it. Any issues, we always can fix them.

**Comment by deitch** [comment]
CI is displeased.

**Comment by amarcum** [comment]
Hopefully that one liner makes the CI happy again!
It took a while, but I have also figured out (through way too much trial and error!) how to automatically increment version tags, create a release page in GitHub, and upload a few OS/Platform combos. It might be a worth while update to the existing GitHub Actions file.  It also might be good to squash the many attempts to get it working on a PR ;)
This is what the releases page would look like: https://github.com/amarcum/go-pcap/releases
This is the only relivant change between this PR and the updated GitHub Actions: https://github.com/amarcum/go-pcap/blob/master/.github/workflows/main.yml

**Comment by deitch** [comment]
Sure, I like the idea of automatic releases on tags. It should be its own file, which makes it much easier to make the whole workflow dependent on tags.

Let's get the CI here happy first, though, then we can do a separate PR.

**Comment by deitch** [comment]
Looks like that still didn't get it. 🤷‍♂️

**Comment by amarcum** [comment]
It might help if we don't try to lint all dependencies in go/pkg/mod... That was not so smart of me... This only showed up because we ran the test in a docker container with the go/pkg/mod directory locally mounted in our github.workspace directory which is also the top level of our code... oops.

**Comment by amarcum** [comment]
Grr... New version of Go requires new linter...

**Comment by deitch** [comment]
CI is clean! Huzzah! Are you ready to go with this @amarcum ?

**Comment by amarcum** [comment]
Yup, let's merge!

**Review by deitch — APPROVED** [review]

**Pull request merged**
